repos:

  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3.9
        exclude: >
          (?x)^(
            scripts/gen-docs-index|
          )$

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        exclude: deploy/
      - id: debug-statements
      - id: detect-private-key
      - id: fix-encoding-pragma
      - id: flake8
      - id: trailing-whitespace


