repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        exclude: deploy/
      - id: debug-statements
      - id: detect-private-key
      - id: fix-encoding-pragma
      - id: flake8
      - id: trailing-whitespace


