version: 2.1
jobs:
  build:
    docker:
      - image: amazonlinux:2
    steps:
      - checkout
      - run:
          name: make
          command: |
            sudo yum install make
            make all
