version: 2.1

executors:
  build:
    resource_class: arm.medium
    machine:
      image: ubuntu-2004:current
  pre-commit-test:
    docker:
      - image: cimg/python:3.9.13

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  build:
    executor: build
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: WEB-IDENTITY-PROFILE
          role-arn: CIRCLECI_ROLE_ARN
          role-session-name: example-session
      - run:
          name: "make zip"
          command: make all
      - run:
          name: sync zip file
          command: aws s3 get-login-password --region AWS_DEFAULT_REGION --profile WEB_IDENTITY_PROFILE sync ./build/ 's3://immortal-soup-59'

  pre-commit-deps:
    executor: pre-commit-test
    steps:
      - checkout
      - run: pip3 install pre-commit
      - run: pre-commit install-hooks

  pre-commit-test:
    executor: pre-commit-test
    steps:
      - checkout
      - run: pip3 install pre-commit
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files

workflows:
  version: 2

  make-sync-zip:
    jobs:
      - pre-commit-deps
      - pre-commit-test:
          requires:
            - pre-commit-deps
      - build:
          context:
            - aws
          requires:
            - pre-commit-test