version: 2.1
jobs:
  build:
    docker:
      - image: nickseldnersp/arm64-clamav:arm64v8
        auth:
          username: nickseldnersp
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run: |-
            ll
