version: 2.1
jobs:
  build:
    docker:
      - image: amazonlinux:2
    steps:
      - checkout
      - run:
          name: make
          command: |
            yum install -y yum-utils
            yumdownloader --archlist=aarch64 make
            make all