version: 2.1

executors:
  build:
    resource_class: arm.medium
    machine:
      image: ubuntu-2004:current
  pre-commit-test:
    docker:
      - image: cimg/python:3.9.13

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  build:
    executor: build
    steps:
      - checkout
      - run:
          name: "make zip"
          command: make all

  aws-cred-set-and-sync:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
      - aws-s3/sync:
          from: ./build/
          to: 's3://immortal-soup-59'

  pre-commit-deps:
    executor: pre-commit-test
    steps:
      - checkout
      - run: pip3 install pre-commit
      - run: pre-commit install-hooks

  pre-commit-test:
    executor: pre-commit-test
    steps:
      - checkout
      - run: pip3 install pre-commit
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files

workflows:
  version: 2

  make-sync-zip:
    jobs:
      - pre-commit-deps
      - pre-commit-test:
          requires:
            - pre-commit-deps
      - build:
          requires:
            - pre-commit-test