version: 2.1
jobs:
  build:
    resource_class: arm.medium
    machine:
      image: ubuntu-2004:current

    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: |
            sudo apt update
            sudo apt -y install dnf
            sudo dnf install -y cpio python3-pip yum-utils zip unzip less
            sudo dnf install -y amazon-linux-extras
            sudo subscription-manager repos --enable codeready-builder-for-rhel-8-$(arch)-rpms
            sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
            echo "complete!"