version: 2.1

setup: true

defaults: &defaults
  working_directory: /tmp/ci-test

orbs:
  continuation: circleci/continuation@0.1.2
  aws-cli: circleci/aws-cli@3.1

executors:
  version-check:
    docker:
      - image: amazonlinux:2

jobs:
  evaluate:
    <<: *defaults
    executor: version-check
    steps:
      - run: mkdir -p workspace
      - run: |
          yum update -y
          yum install tar -y && yum install gzip -y
          yum makecache fast
          echo CLAMAV_LATEST=$(yum info clamav-update | grep Version | awk -F':' '{ print $2 }' | tail -n1 | tr -d '[:space:]') >> workspace/clamav-latest

      - run:
          name: creating json object
          command: |
           echo {\"clamav-version\": \"${CLAMAV_LATEST}\"\} >> workspace/output.json
      - persist_to_workspace:
          root: workspace
          paths:
            - clamav-latest

  setup:
    <<: *defaults
    executor: continuation/default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/ci-test/workspace
      - run: ls -lah && pwd
      - run: cat workspace/clamav-latest >> $BASH_ENV
      - run:
          name: use job config
          command: |
            echo "using job config"
      - continuation/continue:
          configuration_path: ./scripts/new-config.yml
          parameters: /tmp/ci-test/workspace/output.json

workflows:
  version: 2
  load-env-setup:
    jobs:
      - evaluate
      - setup:
          requires:
            - evaluate