version: 2.1
jobs:
  build:
    docker:
      - image: amazonlinux:2
    steps:
      - checkout
      - run:
          name: make
          command: |
            yum install -y amazon-linux-extras
            amazon-linux-extras install -y epel
            make all
