version: 2.1
jobs:
  build:
    docker:
      - image: amazonlinux:2
    steps:
      - checkout
      - run: |-
            yum install -y make docker
            service docker restart
            usermod -a _G docker ec2-user
            make all
            ll
