version: 2.1
jobs:
  build:
    docker:
      image: nickseldnersp/arm64-clamav:1
      auth:
        username: nickseldnersp
        password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: |
            yum update -y
            yum install -y cpio python3-pip yum-utils zip unzip less
