version: 2.1

setup: true

defaults: &defaults
  working_directory: /tmp/ci-test

orbs:
  continuation: circleci/continuation@0.1.2
  aws-cli: circleci/aws-cli@3.1

executors:
  version-check:
    docker:
      - image: amazonlinux:2

jobs:
  evaluate:
    <<: *defaults
    executor: version-check
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: |
          yum update -y
          yum install tar -y && yum install gzip -y && yum install unzip -y
          yum makecache fast
      - aws-cli/setup:
          role-arn: $CIRCLECI_ROLE_ARN

      - run: |
          export CLAMAV_LATEST=$(yum info clamav-update | grep Version | awk -F':' '{ print $2 }' | tail -n1 | tr -d '[:space:]')
          echo CLAMAV_LATEST=$CLAMAV_LATEST >> workspace/clamav-latest
          export REQUIRE_UPDATE=$(aws s3 ls s3://immortal-soup-59/lambda-$CLAMAV_LATEST.zip > /dev/null; if [[ $? == 0 ]]; then echo false; else echo true; fi)
          echo '{"require-update": '$REQUIRE_UPDATE'}' >> workspace/require-update.json
          echo $REQUIRE_UPDATE $CLAMAV_LATEST
      - persist_to_workspace:
          root: workspace
          paths:
            - clamav-latest
            - require-update.json

  setup:
    <<: *defaults
    executor: continuation/default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/ci-test/workspace
      - run: cat workspace/clamav-latest >> "$BASH_ENV"
      - run:
          name: use job config
          command: |
            ./scripts/new-config $CLAMAV_LATEST
      - continuation/continue:
          configuration_path: ./configs/generated_config.yml
          parameters: /tmp/ci-test/workspace/require-update.json

workflows:
  version: 2
  load-env-setup:
    jobs:
      - evaluate:
          context:
            - aws
      - setup:
          requires:
            - evaluate