version: 2.1
jobs:
  build:
    resource_class: arm.medium
    machine:
      image: ubuntu-2004:current

    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: |
            sudo apt-get update
            sudo service docker restart
            make all
            ll