version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    resource_class: arm.medium
    machine:
      image: ubuntu-2004:current
  
    steps:
      - checkout
      - run: 
          name: "make zip"
          command: make all

      - aws-s3/sync:
          from: ./build/lambda.zip
          to: 's3://immortal-soup-59'
  
  pre-commit-deps:
    steps:
      - checkout
      - run: pip install pre-commit
      - run: pre-commit install-hooks
  
  pre-commit-test:
    steps:
      - checkout
      - run: pip install pre-commit
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files

workflows: 
  make-sync-zip:
    jobs:
      - pre-commit-deps
      - pre-commit test:
          requires:
            - pre-commit-deps
      - test
      - build:
        requires:
          - pre-commit-test
          - test