version: 2.1
jobs:
  build:
    docker:
      - image: amazonlinux:2
    steps:
      - run:
        name: install git
        command: |
          sudo yum install git
          git clone https://github.com/nicks-sp/bucket-antivirus-function.git
          cd bucket-antivirus-function
      - run:
        name: make zip
        command: |
          make all
          