version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: generate config
          command: |
            ./scripts/new-config
      - continuation/continue:
          configuration_path: ./scripts/new-config/configs/generated_config.yml

workflows:
  setup:
    jobs:
      - setup