version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: use job config
          command: |
            echo "using job config"
      - continuation/continue:
          configuration_path: ./scripts/new-config.yml

workflows:
  setup:
    jobs:
      - setup